---
- name: OS-specific setup (Debian/Ubuntu)
  block:
    - name: Install prerequisites
      ansible.builtin.apt:
        name: software-properties-common
        state: present
        update_cache: yes

    - name: Add deadsnakes PPA for latest Python
      ansible.builtin.apt_repository:
        repo: ppa:deadsnakes/ppa
        state: present

    - name: Install Development Tools
      apt:
        name: "{{ dev_env_packages_debian }}"
        state: present
        update_cache: yes

  when: ansible_os_family == "Debian"

- name: OS-specific setup (Alpine)
  block:
    - name: Install Development Tools
      apk:
        name: "{{ dev_env_packages_alpine }}"
        state: present
        update_cache: yes
  when: ansible_os_family == "Alpine"

- name: Set Zsh as default shell for primary user
  user:
    name: "{{ primary_user }}"
    shell: /usr/bin/zsh
