---
- name: Deploy Pi-hole v6 on Ubuntu LXC
  hosts: proxmox
  gather_facts: no
  vars:
    lxc_type: "pihole"
    lxc_index: 1
    lxc_memory: 1024
    lxc_cores: 2
    lxc_disk_size: "10G"

  roles:
    - role: lxc-ubuntu

- name: Install Pi-hole (Bare Metal / Ubuntu)
  hosts: "{{ lxc_hostname | default('pihole_hosts') }}"
  become: true

  roles:
    - pihole
