---
traefik_version: "v3.0"
traefik_is_gateway: false
traefik_domain: "in.s3ntin3l8.de" # Default domain
traefik_config_path: "/etc/traefik"

# SSL / Cloudflare (Gateway only)
traefik_cf_email: "s3ntin3l8@gmail.com"
traefik_cf_api_key: "4dd3d9ab4db2723b3ba109c2ccaad62d4338a"

# Networking
traefik_gateway_ip: "192.168.1.100" # Placeholder, will be set by playbook/inventory
traefik_trusted_ips:
  - "127.0.0.1/32"
  - "{{ traefik_gateway_ip }}/32"

# Dashboard
traefik_dashboard_enabled: true
